### ISSUE TITLE
No Popup after install - no section to see anything

### ISSUE THREAD

**Issue by weide-git** [KristianOellegaard/homeassistant-stokercloud#3]
Even after a restart there is nothing I can do. Is there something I have to do additionally?

Regards,
Michael

**Comment by KristianOellegaard** [comment]
I haven't had any issues. Is this a new install on the newest HA?

**Comment by weide-git** [comment]
Yes, completely fresh. I also tried to reinstall - eben no popup telling it my Stokercloud name.

Regards

Am 23. Juli 2022 17:22:35 MESZ schrieb "Kristian Øllegaard" ***@***.***>:

**Comment by weide-git** [comment]
I was able to install it successfully. Sry
