### ISSUE TITLE
Udvidet "install guide" til nybegyndere

### ISSUE THREAD

**Issue by mikkelmoell** [KristianOellegaard/homeassistant-stokercloud#4]
Først og fremmest - mega fedt du har taget dig tid til at lave denne integration!

Jeg er "nybegynder", generelt med Home Assistant, og kan ikke rigtig komme videre efter selve installationen af integrationen via HACS. Der kom ikke et felt op, hvor jeg skulle skrive mit stokercloud.dk brugernavn.

I diverse python filer henvises der til: from homeassistant.const import CONF_USERNAME"
Har forsøgt selv at lave filen og definere: CONF_USERNAME = "BRUGERNAVN"

Lige lidt har det hjulpet, men det kan også sagtens være mig der bare ikke forstår hvordan det skal/burde virke.

Kan du eventuelt udvide din "installations guide" med specifikke steps til opsætning?

**Comment by KristianOellegaard** [comment]
Hej,

Det skulle nu altså gerne poppe op når du tilføjer integrationen:

![image](https://user-images.githubusercontent.com/235775/203929834-4818c1fe-ef02-45f3-814a-c45939592a25.png)

![image](https://user-images.githubusercontent.com/235775/203929864-02b2a826-64f8-4094-822c-de436eba18c5.png)


Mvh
Kristian

**Comment by mikkelmoell** [comment]
> Hej,
> 
> Det skulle nu altså gerne poppe op når du tilføjer integrationen:
> 
> ![image](https://user-images.githubusercontent.com/235775/203929834-4818c1fe-ef02-45f3-814a-c45939592a25.png)
> 
> ![image](https://user-images.githubusercontent.com/235775/203929864-02b2a826-64f8-4094-822c-de436eba18c5.png)
> 
> Mvh Kristian

Beklager min svartid :)

Du har så fuldstændig ret. Det manglende i mit tilfælde var bare, at jeg skulle forstå, at når man har tilføjet integration via HACS, skal man ind og finde og tilføje det som "alm integration" i HA. Som nævnt nybegynder med HA :).

Tak for hjælpen :).
